name: MMM CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20

        uses: actions/setup-node@v3

        with:
          node-version: '20.11.0'

      - name: Install dependencies (server)

        run: |
          cd server 
          npm ci

      - name: Run tests
        run: |
          cd server 
          npx jest

      - name: Login to DockerHub

        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (server)

        uses: docker/build-push-action@v2

        with:
          context: server

          push: true

          tags: faissal454/server_hub:latest

      - name: Build and push Docker image (client)

        uses: docker/build-push-action@v2

        with:
          context: client

          push: true

          tags: faissal454/client_hub:latest
